spring.application.name=MSCommandes
server.port=8090

# Config Server — récupère la config depuis http://localhost:8888
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/MY2TEK_commandes_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# RabbitMQ
rabbitmq.enabled=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# Noms des queues RabbitMQ
commandes.rabbitmq.queue=commandes.queue
commandes.rabbitmq.exchange=commandes.exchange
commandes.rabbitmq.routingkey=commandes.routingkey

# Feign — désactiver circuit breaker (UserMicroService peut être absent)
spring.cloud.openfeign.circuitbreaker.enabled=false

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
