version: '3.9'

services:

  eureka-server:
    build: ./eureka
    image: islembouch/eureka:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  config-server:
    build: ./config-server
    image: islembouch/configserver:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-commandes:
    build: ./MS_Commandes
    image: islembouch/ms-commandes:1.0
    container_name: ms-commandes
    ports:
      - "8090:8090"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
      - SPRING_CLOUD_CONFIG_RETRY_ENABLED=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=10
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=3000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MY2TEK_commandes_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/MY2TEK-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/MY2TEK-realm/protocol/openid-connect/certs

  API-gateway:
    build: ./apigetway
    image: islembouch/apigateway:1.0
    container_name: gateway
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - config-server
      - ms-commandes
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/MY2TEK-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/MY2TEK-realm/protocol/openid-connect/certs

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MY2TEK_commandes_db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    container_name: keycloak
    restart: always
    command: start-dev --http-port=8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8100:8080"
    volumes:
      - ./data/keycloak:/opt/keycloak/data

  user-microservice:
    build: ./UserMicroService
    image: islembouch/user-microservice:1.0
    container_name: user-microservice
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MY2TEK_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/MY2TEK-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/MY2TEK-realm/protocol/openid-connect/certs
      - KEYCLOAK_ADMIN_SERVER_URL=http://keycloak:8080

  product-microservice:
    build: ./Product-MS
    image: islembouch/product-microservice:1.0
    container_name: product-microservice
    ports:
      - "8086:8086"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MY2TEK_product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ms-competence-review:
    build: ./MS_CompetenceAndReview
    image: islembouch/ms-competence-review:1.0
    container_name: ms-competence-review
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MY2TEK_competence_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  shipping-microservice:
    build: ./ShippingMicroService
    image: islembouch/shipping-microservice:1.0
    container_name: shipping-microservice
    ports:
      - "8091:8091"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MY2TEK_shipping_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
