spring.application.name=apigetway
server.port=8085

spring.config.import=optional:configserver:

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ? Remove all the globalcors lines ? handled by SecurityConfig now
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8100/realms/MY2TEK-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8100/realms/MY2TEK-realm/protocol/openid-connect/certs