# ── Shipping Microservice Config (served by Config Server) ──

welcome.message=Welcome to ShippingMicroService - MY2TEK

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/MY2TEK_shipping_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghassenben9@gmail.com
spring.mail.password=kltx cqnz guir luve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
management.endpoints.web.exposure.include=health,info

# Spring RabbitMQ
spring.rabbitmq.host=localhost
# port par défaut du protocole AMQP
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
